### ISSUE TITLE
Disable stacktrace mode

### ISSUE THREAD

**Issue by sdeleuze** [danielfernandez/test-spring-boot-reactive-netty-output#1]
Reactor stacktrace mode, a feature that allows to get useful stacktraces (with a significant performance impact), is enabled by default. It should be disabled for benchmarks via the `spring.reactor.stacktrace-mode.enabled=false`.

I tend to think we should disable it by default (see https://github.com/bclozel/spring-boot-web-reactive/issues/53) but we need to discuss that with the team.

The impact of the performance is huge, for example with SSE on Tomcat:
 - With default configuration: 1 min 57 seconds
 - With spring.reactor.stacktrace-mode.enabled=false: 1 second

**Comment by sdeleuze** [comment]
Thanks to [this commit](https://github.com/bclozel/spring-boot-web-reactive/commit/4073375a48db84f94d90e07f29302766223bce26), stacktrace mode is only enabled when devtools is on the classpath, so you should get good performances by default now!

**Comment by danielfernandez** [comment]
Thanks @sdeleuze , but I'm wondering... this trace mode was enabled for both SSE and non-SSE. So now it is disabled, if we simply increase the returned collection size (say, to `100000`) in order to get more measurable times, wouldn't we still experience an important difference between SSE and non-SSE response times? or did this trace mode affect SSE mode more than non-SSE mode?

**Comment by sdeleuze** [comment]
SSE is using more operators, that why it was strongly impacted with stackstrace mode. Now it is disabled,  with `100000` repetitions I get 13 seconds with SSE and 4 seconds with non SSE, which seems to me reasonable given tranformations + more data emitted + huge number of flushes performed for SSE.

**Comment by danielfernandez** [comment]
Reactor StackTrace mode now disabled for all 5 servers. Thanks.

**Comment by sdeleuze** [comment]
You're welcome. Notice that with latest `spring-boot-web-reactive` snapshots the stacktrace mode is only enabled by default if you have Spring Boot devtools on the classpath.
